# Generated by Django 4.2.2 on 2023-07-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0002_comment_recommended_videos_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
