# Generated by Django 4.2.2 on 2023-07-05 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0005_rename_comment_comment_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommended_videos',
            name='video',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='youtube_clone.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommended_videos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube_clone.user'),
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='youtube_clone.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='youtube_clone.user'),
            preserve_default=False,
        ),
    ]
