# Generated by Django 4.2.3 on 2023-07-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0007_comment_like_num_reply_like_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='recommended_Video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube_clone.video'),
        ),
        migrations.DeleteModel(
            name='Recommended_Videos',
        ),
    ]
