# Generated by Django 4.2.3 on 2023-07-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0009_remove_video_recommended_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='recommended_Video',
        ),
        migrations.CreateModel(
            name='Recommended_Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_videos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_videos', to='youtube_clone.video')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_videos', to='youtube_clone.video')),
            ],
        ),
    ]
