# Generated by Django 4.2.3 on 2023-07-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0011_remove_recommended_videos_recommended_videos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended_videos',
            name='recommended_videos',
            field=models.ManyToManyField(related_name='recommended_videos', to='youtube_clone.video'),
        ),
    ]
