# Generated by Django 4.2.3 on 2023-07-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0012_alter_recommended_videos_recommended_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
